### PR TITLE
Translating messages into Korean.

### PR DESCRIPTION
**Pull request by cwdoh**
I've translated messages into Korean.
* **Quick questions**:
 * `messages.json` doesn't include all strings on it. Is there anything I have to find them?

### CODE REVIEW

**Comment by MarkusBordihn** [comment]
Thanks. At the moment we have not automated the i18n files, but I will update the files in the next days.

Alternative you could use the following process for additional strings:
https://github.com/google/coding-with-chrome/blob/master/doc/I18N.md

**Comment by cwdoh** [comment]
@MarkusBordihn yes, I did it, and now I understand this project would be in progress. I'll follow next updates. :)

**Comment by MarkusBordihn** [comment]
@cwdoh 
Just to let you know that I have finalized the new translation system.

You will find a list of the current supported text under '/src/locales/en/translation.js':
https://github.com/google/coding-with-chrome/blob/master/src/locales/en/translation.js

Fell free to add these to 'src/locales/ko/translation.js':
https://github.com/google/coding-with-chrome/blob/master/src/locales/ko/translation.js

If you want you could also add you as @author for the '/ko/translation.js' file in the comments.

**Comment by cwdoh** [comment]
@MarkusBordihn Awesome!! Much better than before. I'll do it soon. :)

**Pull request merged**
