### PR TITLE
Proxy dialog

### PR DESCRIPTION
**Pull request by adamcarheden**

### CODE REVIEW

**Comment by MarkusBordihn** [comment]
Whats the different to the existing dialog options like:
cwc.utils.Dialog.prototype.showAlert
cwc.utils.Dialog.prototype.showPrompt

This kind of modal inputs are already used for Python 2, see cwc.framework.Python2.

**Comment by adamcarheden** [comment]
@MarkusBordihn 

I didn't realize that functionality was already used in the Python2.7 mode so I had to look into how it works. It appears that Skulpt works a bit differently than Brython. In Skulpt, we [assign our showInput function to Skulpt's 'inputfun' parameter](https://github.com/google/coding-with-chrome/blob/620882e4559b9a0ca13cb28f87657b15e70694ad/src/frameworks/python/python2.js#L78), which Skulpt then calls when the user's code calls Python's input().

Byrthon instead calls Javascript's prompt() function. WebView blocks prompt() and alert(), but it does fire the ondialog event on the webview object, which we can listen for. Unfortunately CwC's dialog event is modal to the entire CwC UI and we don't currently have a way to disable auto-execute, so using input() in Python3 would continuously pop up a dialog with each keystroke that the user would have to close before continuing to code.

Alternatives considered:

1) I could refactor the CwC dialog to optionally take an element to it's constructor and sit atop only that element instead of the entire UI. We would then pass the preview div as that element to the dialog preview instance. I did try this first, but various parts of cwc.utils.dialog seem to be meant to be a singleton, especially the CSS, so I eventually decided creating a new preview dialog class would be easier.

2) I tried assigning a custom function to window.prompt inside the Python3 cwc framework that calls dialog.showPrompt(). However, window.prompt expects a synchronous function and showPrompt() returns a promise. Assigning it an asynchronous function doesn't work. The code gets executed, but Python's input() always ends up returning the string '[object Promise]' immediately.

3) If there was a way to intercept prompt() inside the WebView, we could have that event handler just use cwc.utils.dialog. However, I can't find any event handler that first on prompt(). Please let me know if you know of one. I only see the one used in this PR that fires on the webview itself, which executes in the main CwC context.

4) I though about refactoring this PR to run inside the webview by moving it to the Python3 framework, but I think I'd have the same problem as in 2 above -- prompt has to be a synchronous function, but the only way I can get input from the user is by listening to some event, which is necessarily asynchronous. (Possibly I'm just thinking about Promises incorrectly. Let me know if that's the case.)

5) I could listen to the ondialog event but instead of displaying a dialog I could pass a message back into the webview. The Python3 framework would listen for that message and call cwc.utils.dialog.showPrompt(). When that promise resolved, it would then pass another message back out of the webview, which the main CwC code would be listening for. That would then call the ondialog event's ok() function with the user's input that it gets from the message passed back out of the webview via the messaging API. That seems like a complicated solution to what should be simple problem.

Of these, I think #1 is the best solution, but this copy of cwc.utils.dialog was the easier path to demonstrate the problem and a solution. Let me know if you'd prefer any of the options above.

**Comment by MarkusBordihn** [comment]
@adamcarheden 
I would prefer to have as less copies of similar functionally as possible like solution 1.
But I also understand if refactoring is to much work and you want to keep a separate version instead.

**Review by crypt096 — CHANGES_REQUESTED** [review]
Build is failing. Please investigate.

**Pull request closed without merging**
