### PR TITLE
Minor formatting updates to READM.md.

### PR DESCRIPTION
**Pull request by carlosperate**
A very minor PR adding break lines to the markdown file improve readability.

### CODE REVIEW

**Comment by carlosperate** [comment]
Before I agree on anything (specially for such a silly PR), is this going to fail if my git commits email is not my google account? I am using the [Keep your email private](https://help.github.com/articles/keeping-your-email-address-private/) feature, and I am not really going to change that.

On top of that, the https://cla.developers.google.com/ doesn't let you switch google accounts before proceeding...

**Comment by MarkusBordihn** [comment]
Unfortunately this is an automated thing, which could not be bypassed.

I'm not sure about the "Keep your email private" feature, but feel free to test it.
The data which are used by the Googlebot not including any email alias.

But fell free to close this pull request and I will reformat the README file in the next days.

**Comment by MarkusBordihn** [comment]
Ok checked this with an colleague, seems the email needs to match. Sorry. :/

**Comment by carlosperate** [comment]
That's really unfortunate, as I am very hesitant to push to github with my personal email :(

Would you be able to at least send some feeback to the team responsible to see if they can allow developers to switch google accounts on the https://cla.developers.google.com/ page? The majority of google apps let you do this, but it looks like in this case I would have to sign out with one account for the other to "log in" to the CLA page.

**Comment by MarkusBordihn** [comment]
I will forward your feedback to the corresponding team.

**Comment by carlosperate** [comment]
Thank you Markus.

**Pull request closed without merging**
