### PR TITLE
Added What's New! banner

### PR DESCRIPTION
**Pull request by adamcarheden**

### CODE REVIEW

**Comment by MarkusBordihn** [comment]
It should be still separated as module and not be hacked into the select screen for several reasons.
The select screen is use to select the different modes, the whats new feature is not really fitting into this concept and should be ideal completely separated from the select screen.

Ideal it should be located under src/ui/whats_new_screen/ which will be showed once after the start as an overlay of the select screen, but not as part of it.

**Comment by adamcarheden** [comment]
> It should be still separated as module and not be hacked into the select screen for several reasons.
> The select screen is use to select the different modes, the whats new feature is not really fitting into this concept and should be ideal completely separated from the select screen.
> 
> Ideal it should be located under src/ui/whats_new_screen/ which will be showed once after the start as an overlay of the select screen, but not as part of it.

Patch set 3 puts it in a separate directory. The select screen still needs to call it. Existing changelog code is part of src/ui/help, so I left that in place. That also calls a method to initialize the checkbox.

**Comment by MartenvanWezel** [comment]
FWIW I would like it in the select screen. For I suspect many people
(myself included) this screen is still the default. I don't want to ambush
people after they boot CWC because that is very interruptive if they are
already on their journey to the mode they want.

If I'm wrong and weird for leaving the select screen then nobody will see
it anyway.

Note: I am not super fierce about this but I really think it's bad design
to remove it from the first screen many users see (especially new users)

-M

**Comment by adamcarheden** [comment]
Markus,

I think PS 3 does the code separation adequately, but let me know if if it
doesn't. It still doesn't the check every time it displays a select screen
template, but I think only welcome, normal and advanced call that function,
all of which need to do the check.

**Pull request merged**
