### PR TITLE
Add a field for addons to store data in .cwc files

### PR DESCRIPTION
**Pull request by adamcarheden**
How about this as a way to addons to store data in cwc files? It just adds a field to file_format. It includes unit tests and an example add-on that displays a message in the message pane.

You can try out an example file at static_files/resources/examples/simple/message/message.cwc. You'll need to use the file open dialog, as there's nothing in the select screens that point to that file.

Note that my plan to add a tutorial feature needs some place to store it's data, so this seemed like a minimally intrusive way to modify the .cwc file format both for that purpose and future features that can be implemented as add-ons.

### CODE REVIEW

**Comment by adamcarheden** [comment]
I just noticed and fixed some Closure compiler errors in the latest commit to the requested pull.

**Comment by MarkusBordihn** [comment]
In general the data of addons should be independent of the .cwc files.
Otherwise the .cwc files would be failed to load if users deactivated the addons or using an older version.

To store data, I just submitted an basic "database" utils. This database library creates an unique DB which could be used for each addon and could store blob files as well.

The big advantage is that the native IndexDB is optimized for data and performance and is much better then any custom implementation.

At the moment the "description" field is not really represented on the UI, feel free to adjust your PR to represent the "description" field in the core UI instead.

**Comment by adamcarheden** [comment]
Tutorial data being independent of .cwc files is the opposite of how I understood the intent of the feature. Are we not providing a framework for independent content creators to develop programming tutorials that cwc will display? If so, cwc will need to read tutorial data from an external source.

IndexDB just lets us store data in the user's browser, but where does it come from in the first place? If we're preserving the ability to operate offline, it needs to be either in a .cwc file or some new file format.

As for older versions, try opening static_files/resources/examples/simple/message/message.cwc with cwc compiled using the master branch. It works fine. The PR simply adds a new field to the top level of the JSON. file_format only cares about the fields it knows about and happily ignores any others (great design, by the way). Unless the the current code has been significantly reorganized since some past version I'm not sure what would break.

As for disabling addons, I don't see a way to do that at the moment, but there probably should be just as there is for modules. It would be up to the addon author to validate addon data exit cleanly if its not there (i.e. if (!file.getAddon()['myaddon']) { //validate here } else { return; }). But addons need to be submitted to this project as a PR and built in rather than something the user downloads (which would be a horrible security risk), so they would be vetted like any other code.

The purpose of this PR was to encapsulate all future changes addons need to make to the .cwc file format into a single field that cwc provides to addons as unmarshaled json. That way this should be the only change we would need to make to the cwc core to support future addons.

**Comment by MarkusBordihn** [comment]
Only to understand this correctly, at the moment I see two main use cases for such feature:

1. Data are downloaded from an external source (user is online) to an local storage like indexedDB.
This step needs to be done only once and should only take a 1-5 second or so. 

2. Data are loaded from static files (user is offline / addon directoy) to an local storage like indexedDB.
This step also needs only to be done once and should only take 1-3 seconds or so.

The second approach is already done with the framework files.
All static frameworks are loaded during the start into the memory (will be moved to indexedDB) and used from here.

From your last update it sounds like you want a additional approach like:

3. User adding additional tutorial content (which are not part of the code base) and loaded this file directly into CWC.

In general the last approach would be possible, but we would need to separate these files from the normal .cwc files like .cwct files or we need to make sure that these information are remove if the user save the example to GoogleDrive, Cloud Storage or exporting the code in any way.

Please let me know if this is correct and if you want so support all three use-cases or only some of these use-cases. Thanks a lot.

**Comment by adamcarheden** [comment]
Use case 3 is what I had been imagining. I hadn't considered the case of
saving a file.

We could just give add-ons a save event that lets the add-on decide if it's
content gets saved. In the case of a tutorial, it wouldn't since we don't
yet have a tutorial editor and any modified content might no longer make
sense with the tutorial content. A new file extension seems like a
reasonable approach as well.

I'll be glad to code a PR for either a new file format or a save event on
this PR.

In any case, this PR still seems like a useful way to let add-ons add to
the .cwc file format, but not a prerequisite for the tutorial feature if I
just so a new file format.

**Comment by MarkusBordihn** [comment]
For this specific use case, please adjust your PR a little bit.

The new field should be called "metadata" and should have the following options:
setMetadata(name, value, namespace = 'default')
getMetadata(name, namespace = 'default')

Datastructur:
metadata = {
  'namespace:' {
    'name': '...',
  },
}

This allows every application to store metadata in the file format.
An adone could use their own namespace to make sure no data are overwritten by another addon or so.

**Comment by adamcarheden** [comment]
The addon field has been renamed to metadata and the API refactored to use the name/namespace parameters.

@MarkusBordihn, what's your thought on using the metadata feature for tutorials vs a different file format? Either is fine with me.

**Comment by MarkusBordihn** [comment]
For the tutorials I still recommend a different file to make sure that the .cwc files are not overloaded with data.
The other reason is that tutorials should be independent from normal files for maintenance reason.

**Pull request merged**
