### PR TITLE
Added simpler tutorial developer interface

### PR DESCRIPTION
**Pull request by adamcarheden**
Markus,

Please take a look at this change to the tutorial feature. It's a precursor to multi-step tutorials. I've added markdown support and a place for messages at the top of the sidebar. validatePreview() can now just return a string that gets displayed there. Full HTML support in a webview is retained to support more complex use cases as well.

A few things I may need to fix before you merge:
* The tutorial content is rendered in a webview even if it's in markdown. We'd have to trust the `marked` library to properly sanitize user-provided content to avoid a webview/iframe, so using one still seems like the correct solution to me.
* I used window['marked'] instead of just 'marked' because I couldn't figure out how to get the linter to recognized 'marked' as defined.
* I copied some colors to the css of message at the top of the tutorial sidebar. These should probably be inherited from some other styles somehow, but I couldn't figure out a good way to do that.
* Sidebar.showRawContent() is now unused. I left it in since it's working code, but perhaps it should be deleted.

### CODE REVIEW

**Comment by MarkusBordihn** [comment]
Hi Adam,
the closuer-builder has an options to convert .md files to .html so maybe the marked library is not needed in this case. Example:
```
/**
 * Markdown files
 */
closureBuilder.build({
  name: 'CwC Markdown files',
  markdown: [
    'LICENSE.md',
    'NOTICE.md',
  ],
  out: 'genfiles/core/',
});
```
https://github.com/google/coding-with-chrome/blob/master/build/cwc/static_files.js

I agree that the content should be still loaded in an webview instance for performance reasons (separated thread).

I currently working on the terminal integration with debugging options.
This means you could easily inject any type of code to the preview and runner instance without the need of using additional helper.

**Comment by adamcarheden** [comment]
> the closuer-builder has an options to convert .md files to .html so maybe the marked library is not needed in this case

But then what happens when a user opens a .cwct file that uses markdown? That use case requires md to html at runtime, build time. I think we eventually want the community to contribute tutorials rather than being in the content creation business, correct?

**Comment by MarkusBordihn** [comment]
There is already the need to compile the templates files with the build/tutorial.js script.
As long this build script is needed the community would still need to compile their tutorial templates to be able to use them.

I see this integration more for the internal / advanced user usage and would recommend the https://edu.workbencheducation.com/ integration for the community because its easier to use and web based.

**Comment by MarkusBordihn** [comment]
Thanks a lot for the clarification. SGTM.

Please add the "@deprecated" jsdoc with an description like "@deprecated temporary integration until xyz is finalized." to any file / function which falls in this category.

This makes sure that nobody (including me) will make changes to these files and that they are good to remove at a later point.

Please make sure to add marked to https://github.com/google/coding-with-chrome/blob/master/NOTICE.md and let me know when this PR is ready to review.

Thanks.

**Comment by MarkusBordihn** [comment]
You need to add it to https://github.com/google/coding-with-chrome/blob/master/.eslintrc in the global section.

**Comment by adamcarheden** [comment]
Ignore commit #4. I pushed the wrong thing. Fixes coming shortly.

**Comment by MarkusBordihn** [comment]
Thanks.

**Pull request merged**
