### PR TITLE
Notice.md file generated by manually traversing the build/ folder

### PR DESCRIPTION
**Pull request by MartenvanWezel**
Notice.md file is needed for confirming to open source rules.

### CODE REVIEW

**Comment by MartenvanWezel** [comment]
CLA is submitted, I don't know how long this will take, but will monitor.

**Comment by MartenvanWezel** [comment]
Incase there is a robot monitoring this, looking for an exact match:

I signed it!

**Comment by MartenvanWezel** [comment]
OK I've tried altering/updating my email and doing a push/pull again.

**Comment by MartenvanWezel** [comment]
Now says all checks are passed - but well, just to be sure..

I signed it!

**Comment by MarkusBordihn** [comment]
Please remove the "Node.js" part, because its not part of the source / bundled files in any way it.

**Comment by MarkusBordihn** [comment]
Please add the Closure Library, Material design icons and the following fonts as well:
...
OpenSans-Regular.ttf
see https://www.google.com/fonts/specimen/Open+Sans

Roboto-Regular.ttf
see https://www.google.com/fonts/specimen/Roboto
...

**Comment by MartenvanWezel** [comment]
Updated.

**Comment by MartenvanWezel** [comment]
Oh wait, I forgot the Material design library

**Comment by MartenvanWezel** [comment]
Now all done. (oh and yes Closure Library is included too)

**Comment by MarkusBordihn** [comment]
Seems Googlebot not agree with CLA. :(

**Comment by MartenvanWezel** [comment]
It's fine to accept the request, the CLA does not apply to me, so this is purely on a technicality. From now on I think/hope my client is configured correctly (I fixed it after 2 commits here), but this PR is apparently confusing the bot too much to ever pass.

**Comment by MartenvanWezel** [comment]
Wheee

**Pull request merged**
