### PR TITLE
Adding intro video and tutorials for Javascript

### PR DESCRIPTION
**Pull request by ergelo**
Added two examples to Javascript, and a section with Javascript video tutorials. Also added the intro video to the Welcome screen. Bumped version number to match release.

### CODE REVIEW

**Comment by ergelo** [comment]
Probably should be squashed into one commit with the message above.

**Comment by MarkusBordihn** [comment]
Please revert the failing 6529cb5c7b7e6d6541053fab318fe1252f8ad394 for this pull request.

The @author tag at this place is mainly use for the creator of the file.
If you provide an complex function  you could add such @author tag to your created function.

Please also edit the following files to adding the "author" of these files:
* resources/examples/javascript/script/CircleAnimation.cwc
* resources/examples/javascript/script/TriangleAnimation.cwc

**Comment by ergelo** [comment]
@MarkusBordihn PTAL

**Comment by MarkusBordihn** [comment]
@ergelo Please resolve the merge conflict. Let me know if you need any help with this.

**Comment by MarkusBordihn** [comment]
Merged and squashed changes to master.

**Pull request closed without merging**
